apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ranfi-castillo/demo.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
